spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource: 
    name: employee-datasource
    url: jdbc:mysql://localhost:3306/EventManagement
    username: sudipto
    password: sas2nlt1
server:
  servlet: 
    context-path: /event-management-api
